use std::path::{Path, PathBuf};

use crate::doctor::{run_doctor, DoctorInput, DoctorReport};
use crate::error::OmonError;
use crate::platform::Platform;
use crate::Result;

#[derive(Clone, Debug, Default)]
pub struct SetupFlags {
    pub platform: Option<String>,
    pub bot_token: Option<String>,
    pub app_token: Option<String>,
    pub model: Option<String>,
    pub api_key: Option<String>,
    pub anthropic_key: Option<String>,
    pub force: bool,
    pub env_file: Option<PathBuf>,
}

#[derive(Debug)]
pub struct SetupOutcome {
    pub env_path: PathBuf,
    pub report: DoctorReport,
}

pub fn render_env(input: &DoctorInput, platform: Platform) -> String {
    let mut out = String::from(
        "# omon-gateway configuration — generated by `omon-gateway setup`.\n# See .env.example for the full configuration surface.\n\n",
    );
    out.push_str(&format!("OMON_PLATFORM={}\n\n", platform.as_str()));
    match platform {
        Platform::Discord => {
            let token = input
                .discord_tokens
                .first()
                .cloned()
                .unwrap_or_default();
            out.push_str(&format!("DISCORD_BOT_TOKEN={token}\n\n"));
        }
        Platform::Slack => {
            out.push_str(&format!(
                "SLACK_BOT_TOKEN={}\n",
                input.slack_bot_token.as_deref().unwrap_or_default()
            ));
            out.push_str(&format!(
                "SLACK_APP_TOKEN={}\n",
                input.slack_app_token.as_deref().unwrap_or_default()
            ));
            if input.slack_api_base != crate::slack::DEFAULT_SLACK_API_BASE {
                out.push_str(&format!("SLACK_API_BASE={}\n", input.slack_api_base));
            }
            out.push('\n');
        }
    }
    out.push_str(&format!(
        "DEFAULT_MODEL={}\n",
        input.default_model.as_deref().unwrap_or_default()
    ));
    if let Some(key) = &input.openai_api_key {
        out.push_str(&format!("OPENAI_API_KEY={key}\n"));
    }
    if let Some(key) = &input.anthropic_api_key {
        out.push_str(&format!("ANTHROPIC_API_KEY={key}\n"));
    }
    out.push_str(&format!("\nDATABASE_URL={}\n", input.database_url));
    out
}

pub async fn run_setup<F>(
    flags: SetupFlags,
    mut prompt: F,
) -> Result<SetupOutcome>
where
    F: FnMut(&str, Option<&str>) -> Result<String>,
{
    let env_path = flags
        .env_file
        .clone()
        .unwrap_or_else(|| PathBuf::from(".env"));
    if env_path.exists() && !flags.force {
        return Err(OmonError::Config(format!(
            "{} already exists — refusing to overwrite (re-run with --force to replace it)",
            env_path.display()
        )));
    }

    let platform_raw = match flags.platform.clone() {
        Some(platform) => platform,
        None => prompt("Platform — discord or slack", Some("discord"))?,
    };
    let platform = Platform::parse(&platform_raw)?;

    let bot_label = match platform {
        Platform::Discord => "Discord bot token (discord.com/developers/applications -> Bot)",
        Platform::Slack => "Slack bot token (xoxb-..., api.slack.com/apps -> OAuth & Permissions)",
    };
    let bot_token = match flags.bot_token.clone() {
        Some(token) => token,
        None => prompt(bot_label, None)?,
    };
    let app_token = match platform {
        Platform::Slack => match flags.app_token.clone() {
            Some(token) => Some(token),
            None => Some(prompt(
                "Slack app-level token (xapp-... with connections:write, Socket Mode)",
                None,
            )?),
        },
        Platform::Discord => None,
    };
    let model = match flags.model.clone() {
        Some(model) => model,
        None => prompt("Default model", Some("gpt-4o-mini"))?,
    };
    let anthropic = model.starts_with("claude");
    let (key_flag, key_label) = if anthropic {
        (flags.anthropic_key.clone(), "Anthropic API key (blank to skip)")
    } else {
        (flags.api_key.clone(), "OpenAI API key (blank to skip)")
    };
    let api_key = match key_flag {
        Some(key) => Some(key),
        None => {
            let entered = prompt(key_label, None)?;
            (!entered.trim().is_empty()).then_some(entered)
        }
    };

    let mut input = DoctorInput::from_env();
    input.platform_raw = platform.as_str().to_string();
    input.default_model = Some(model);
    match platform {
        Platform::Discord => {
            input.discord_tokens = vec![bot_token];
        }
        Platform::Slack => {
            input.slack_bot_token = Some(bot_token);
            input.slack_app_token = app_token;
        }
    }
    if anthropic {
        input.anthropic_api_key = api_key;
    } else {
        input.openai_api_key = api_key;
    }

    let contents = render_env(&input, platform);
    if let Some(parent) = env_path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent).map_err(|error| {
                OmonError::Config(format!(
                    "cannot create {}: {error}",
                    parent.display()
                ))
            })?;
        }
    }
    std::fs::write(&env_path, contents).map_err(|error| {
        OmonError::Config(format!("cannot write {}: {error}", env_path.display()))
    })?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(&env_path, std::fs::Permissions::from_mode(0o600));
    }

    let report = run_doctor(&input).await;
    Ok(SetupOutcome { env_path, report })
}
